forEnersys/DavePkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AD_Business_Area__c</fullName>
        <label>AD Business Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AD_Industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Rotary wing</fullName>
                </value>
                <value>
                    <fullName>Fixed wing</fullName>
                </value>
                <value>
                    <fullName>Fixed wing - narrow body</fullName>
                </value>
                <value>
                    <fullName>Fixed wing - wide body</fullName>
                </value>
                <value>
                    <fullName>Fixed wing - business jet</fullName>
                </value>
                <value>
                    <fullName>Fixed wing - General aviation</fullName>
                </value>
                <value>
                    <fullName>Trucks</fullName>
                </value>
                <value>
                    <fullName>Tank</fullName>
                </value>
                <value>
                    <fullName>Troop carrier</fullName>
                </value>
                <value>
                    <fullName>Armoured car</fullName>
                </value>
                <value>
                    <fullName>Amphibious vehicle</fullName>
                </value>
                <value>
                    <fullName>Armoured engineering vehicle</fullName>
                </value>
                <value>
                    <fullName>Air defence vehicle</fullName>
                </value>
                <value>
                    <fullName>Surface vessel</fullName>
                </value>
                <value>
                    <fullName>Submarine - diesel electric</fullName>
                </value>
                <value>
                    <fullName>Submarine - nuclear</fullName>
                </value>
                <value>
                    <fullName>Small lift launch vehicle</fullName>
                </value>
                <value>
                    <fullName>Medium lift launch vehicle</fullName>
                </value>
                <value>
                    <fullName>Heavy lift launch vehicle</fullName>
                </value>
                <value>
                    <fullName>Super heavy lift launch vehicle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AD_Distribution_Channel__c</fullName>
        <label>AD Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AD_Industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Armoured Fighting Vehicles [Security]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AD_Industry__c</fullName>
        <label>AD Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Space (Launcher)</fullName>
                </value>
                <value>
                    <fullName>BMS [Battery Monitoring System]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Number_Pick__c</fullName>
        <label>Company #</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Number</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Terms</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Delivery Terms - DT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Accounts (Delivery Terms)</relationshipLabel>
        <relationshipName>Accounts_Delivery_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMEA_CLASS__c</fullName>
        <label>EMEA CLASS</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MP_Business_Area__c</fullName>
        <label>MP Business Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MP_Industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Food Retailers</fullName>
                </value>
                <value>
                    <fullName>Non Food Retailers</fullName>
                </value>
                <value>
                    <fullName>Logistic Operators</fullName>
                </value>
                <value>
                    <fullName>Ports and Warehouses</fullName>
                </value>
                <value>
                    <fullName>FMCG</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Steel and Metal Industry</fullName>
                </value>
                <value>
                    <fullName>Other Industries</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MP_Distribution_Channel__c</fullName>
        <label>MP Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MP_Industry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Truck Dealer</fullName>
                </value>
                <value>
                    <fullName>Battery Dealers and Distributor</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Key End User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MP_Industry__c</fullName>
        <label>MP Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forklifts and Industrial trucks</fullName>
                </value>
                <value>
                    <fullName>AGV-LGV</fullName>
                </value>
                <value>
                    <fullName>Cleaning machines</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Plants</fullName>
                </value>
                <value>
                    <fullName>Other End Users MP</fullName>
                </value>
                <value>
                    <fullName>Rail MP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Payment Terms - PT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Accounts (Payment Terms)</relationshipLabel>
        <relationshipName>Accounts_Payment_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SAP Customer Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Agent_Email__c</fullName>
        <description>Sales Engineer Email from BaaN</description>
        <label>Sales Agent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Terms_of_Delivery_Code__c</fullName>
        <description>BaaN integration</description>
        <label>Terms of Delivery Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Delivery_Desc__c</fullName>
        <description>BaaN Integration</description>
        <label>Terms of Delivery Desc</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Code__c</fullName>
        <description>Customer Master</description>
        <label>Terms of Payment Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Desc__c</fullName>
        <label>Terms of Payment Desc</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/SAP_Reference__c.object
<CustomObject>
    <description>This object is for maintaining the information about delivery terms, payment terms, Incoterms, and other tables of reference from Baan or SAP.</description>
    <fields>
        <fullName>Code_Type__c</fullName>
        <inlineHelpText>Enter the full name of the code type and then follow it with a - and a 2 letter code for the code type</inlineHelpText>
        <label>Code Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Terms_DT</fullName>
                    <label>Delivery Terms - DT</label>
                </value>
                <value>
                    <fullName>Payment_Terms_PT</fullName>
                    <label>Payment Terms - PT</label>
                </value>
                <value>
                    <fullName>Warehouse Codes - WC</fullName>
                </value>
                <value>
                    <fullName>Order Type - OT</fullName>
                </value>
                <value>
                    <fullName>Order Series - OS</fullName>
                </value>
                <value>
                    <fullName>Sales Office - SO</fullName>
                </value>
                <value>
                    <fullName>Customer Group - CG</fullName>
                </value>
                <value>
                    <fullName>Terms of Payment - TP</fullName>
                </value>
                <value>
                    <fullName>Incoterm - IC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>Company #</description>
        <label>Company #</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Number</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>If it begins with B, it is from Baan. If it begins with S, it is from SAP. The second 2 characters describe what type of code it is.</inlineHelpText>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Missing_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked, the record was not previously created and it will need to be addressed in the system of record.</inlineHelpText>
        <label>Missing Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baan</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SAP Reference</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

forEnersys/DavePkg/globalValueSets/Company_Number.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>701</fullName>
    </customValue>
    <customValue>
        <fullName>702</fullName>
    </customValue>
    <description>Legal Entities within EnerSys</description>
    <masterLabel>Company #</masterLabel>
</GlobalValueSet>

forEnersys/DavePkg/classes/AccountUtil.cls
global without sharing class AccountUtil {
	static Map<String,User> userMap;
	static Map<String,SAP_Reference__c> refMap;

    static {
        userMap = new Map<String,User>();
        for ( User u : [ SELECT Id
                        	  , Email
                        	  , IsActive
                           FROM User
                          where IsActive=true] )
        {
            userMap.put( u.Email.toLowerCase(), u );
        }
        
        refMap = new Map<String,SAP_Reference__c>();
        for ( SAP_Reference__c r :  [  SELECT Id
                                            , Code__c
                                            , Code_Type__c
                                            , Key__c
                                         FROM SAP_Reference__c
                                        WHERE Key__c like 'BDT-%'
                                           OR Key__c like 'BPT-%'] )
        {
            refMap.put( r.Key__c, r );
        }
    }

    public static void fixAccount( List<Account> aList ) {
        List<SAP_Reference__c> newRefList = new List<SAP_Reference__c>();
        for ( Account a : aList ) {
            if ( String.isNotBlank(a.Terms_of_Delivery_Code__c) ) {
                String k = 'BDT-'+a.Terms_of_Delivery_Code__c;
                SAP_Reference__c r = refMap.get( k );
                if ( r == null ) {
                    r = new SAP_Reference__c( Code__c = a.Terms_of_Delivery_Code__c
                                            , Name = a.Terms_of_Delivery_Desc__c
                                            , Code_Type__c = 'Delivery Terms - DT'
                                            , Company__c = a.Company_Number_Pick__c
                                            , Key__c = k
                                            , Missing_Value__c = true
                                            , System__c = 'Baan' );
                    newRefList.add( r );
                    refMap.put( k, r );
                }
            }
            if ( String.isNotBlank(a.Terms_of_Payment_Code__c ) ) {
                String k = 'BPT-'+a.Terms_of_Payment_Code__c;
                SAP_Reference__c r = refMap.get( k );
                if ( r == null ) {
                    r = new SAP_Reference__c( Code__c = a.Terms_of_Payment_Code__c
                                            , Name = a.Terms_of_Payment_Desc__c
                                            , Code_Type__c = 'Payment Terms - PT'
                                            , Company__c = a.Company_Number_Pick__c
                                            , Key__c = k
                                            , Missing_Value__c = true
                                            , System__c = 'Baan' );
                    newRefList.add( r );
                    refMap.put( k, r );
                }
            }
        }
        if ( ! newRefList.isEmpty() ) {
            upsert newRefList Key__c;
        }
        for ( Account a : aList ) {
            if ( String.isNotBlank(a.Terms_of_Delivery_Code__c) ) {
                String k = 'BDT-'+a.Terms_of_Delivery_Code__c;
                SAP_Reference__c r = refMap.get( k );
                if ( r != null ) {
                    a.Delivery_Terms__c = r.Id;
                }
            }
            if ( String.isNotBlank(a.Terms_of_Payment_Code__c ) ) {
                String k = 'BPT-'+a.Terms_of_Payment_Code__c;
                SAP_Reference__c r = refMap.get( k );
                if ( r != null ) {
                    a.Payment_Terms__c = r.Id;
                }
            }
            if ( String.isNotBlank(a.Sales_Agent_Email__c ) ) {
                User u = userMap.get( a.Sales_Agent_Email__c.toLowerCase() );
                if ( u != null ) {
                    a.OwnerId = u.Id;
                }
            }
        }
    }

    public static Object passXml( String s ) {
        System.debug(s);
        XmlStreamReader reader = new XmlStreamReader(s);
        if ( reader.hasNext() )
        	reader.next();
        if ( reader.getAttributeValue(null, 'object') == 'true' ) {
            return passXMLObj(reader);
        }
        else if ( reader.getAttributeValue(null, 'array') == 'true' ) {
            return passXMLArray(reader);
        }
        
        String n = reader.getLocalName();
        System.debug(n);
        Map<String,Object> obj = new Map<String,Object>();
        reader.next();
        obj.put( n, reader.getText() );
        return obj;
    }
    
    public static Map<String,Object> passXMLObj( XmlStreamReader reader ) {
        Map<String,Object> obj = new Map<String,Object>();
        if ( reader.hasNext() )
        	reader.next();        
        while ( reader.isStartElement() ) {
            String n = reader.getLocalName();
            System.debug(n);
            if ( reader.getAttributeValue(null, 'object') == 'true' ) {
                obj.put( n, passXMLObj(reader) );
            }
            else if ( reader.getAttributeValue(null, 'array') == 'true' ) {
                obj.put( n, passXMLArray(reader) );
            }
            else {
                reader.next();
                obj.put( n, reader.getText() );
                reader.nextTag();
                reader.nextTag();
            }
        }
        if ( reader.hasNext() )
        	reader.next();
        return obj;
    }
    
    public static List<Object> passXMLArray( XmlStreamReader reader ) {
        List<Object> obj = new List<Object>();
        if ( reader.hasNext() )
        	reader.next();
        while ( reader.isStartElement() ) {
            String n = reader.getLocalName();
            System.debug(n);
            if ( reader.getAttributeValue(null, 'object') == 'true' ) {
                obj.add( passXMLObj(reader) );
            }
            else if ( reader.getAttributeValue(null, 'array') == 'true' ) {
                obj.add( passXMLArray(reader) );
            }
            else {
                reader.next();
                obj.add( reader.getText() );
                reader.nextTag();
            	reader.nextTag();
            }        	
        }
        if ( reader.hasNext() )
        	reader.next();
        return obj;
    }
    
    public static void testtest() {
        Object o = passXml( [select EMEA_CLASS__c from Account where SAP_Customer_Id__c='0000021828'].EMEA_CLASS__c );
        System.debug(o);
    }
    
    
    public static void EmeaClassification(List<Account> aList ) {
        for ( Account a : aList ) {
            if ( String.isBlank(a.EMEA_CLASS__c) ) continue;
            List<Object> o = (List<Object>) passXml( a.EMEA_CLASS__c );
            for ( Object om : o ) {
                Map<String,Object> m = (Map<String,Object>) om;
                String c = (String) m.get('CLASS');
                List<Object> chList = (List<Object>) m.get('CHARACTERISTICS');
                for ( Object ocv : chList ) {
                    Map<String,Object> cv = (Map<String,Object>) ocv;
                    String k = (String) cv.get('ATNAM');
                    String v = (String) cv.get('ATWRT');
                    if ( c == 'CUSTOMERS_AD' ) {
                        if ( k == 'Business area' ) {
                            a.AD_Business_Area__c = v;
                        }
                        else if ( k == 'Industry' ) {
                            a.AD_Industry__c = v;
                        }
                        else if ( k == 'Distribution channel' ) {
                            a.AD_Distribution_Channel__c = v;
                        }
                    }

	                if ( c == 'CUSTOMERS_RP') {
						if ( k == 'Industry' ) {
                            a.AD_Industry__c = v;
                        }
                        else if ( k == 'Distribution channel' ) {
                            a.AD_Distribution_Channel__c = v;
                        }
                    }
                
                	if ( c == 'CUSTOMERS_MP') {
                        if ( k == 'Business area' ) {
                            a.MP_Business_Area__c = v;
                        }
                        else if ( k == 'Industry' ) {
                            a.MP_Industry__c = v;
                        }
                        else if ( k == 'Distribution channel' ) {
                            a.MP_Distribution_Channel__c = v;
                        }
                    }
                }
            }
        }
    }
    
    
    /*
    public static void fixAccountAll() {
        List<Account> aList = [select Id
                              		, Terms_of_Delivery_Code__c
                              		, Terms_of_Delivery_Desc__c
                               		, Delivery_Terms__c
                              		, Terms_of_Payment_Code__c
                              		, Terms_of_Payment_Desc__c
                               		, Payment_Terms__c
                              		, Company_Number_Pick__c
                                    , Sales_Agent_Email__c
                               		, Owner.Email
                                 from Account
                                where Delivery_Terms__c = null
                                  and Payment_Terms__c = null
                                  and ( Terms_of_Delivery_Code__c != null
                                     or Terms_of_Payment_Code__c != null
                                     or Sales_Agent_Email__c != null)
                                limit 2000];
        fixAccount( aList );
        update aList;
    }
	*/
}