forEnersys/DavePkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Number_Pick__c</fullName>
        <label>Company #</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Number</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Agent_Email__c</fullName>
        <description>Sales Engineer Email from BaaN</description>
        <label>Sales Agent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Terms_of_Delivery_Code__c</fullName>
        <description>BaaN integration</description>
        <label>Terms of Delivery Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Delivery_Desc__c</fullName>
        <description>BaaN Integration</description>
        <label>Terms of Delivery Desc</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Code__c</fullName>
        <description>Customer Master</description>
        <label>Terms of Payment Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Desc__c</fullName>
        <label>Terms of Payment Desc</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

forEnersys/DavePkg/globalValueSets/Company_Number.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>701</fullName>
    </customValue>
    <customValue>
        <fullName>702</fullName>
    </customValue>
    <description>Legal Entities within EnerSys</description>
    <masterLabel>Company #</masterLabel>
</GlobalValueSet>

forEnersys/DavePkg/classes/AccountUtilTest.cls
@isTest(SeeAllData=true)

public class AccountUtilTest {
    public static testMethod void testTrigger() {
        List<Account> aList = [select Id
                              	 from Account
                                where Terms_of_Delivery_Code__c != null
                                order by LastModifiedDate Desc
                                limit 1] ;
        Account a;
        if ( aList.isEmpty() ) {
            a = new Account( Name = 'Test Account'
                		   , Terms_of_Delivery_Code__c = 'xyz'
                           , Terms_of_Delivery_Desc__c = 'xyz'
                           , Terms_of_Payment_Code__c = 'xyz'
                           , Terms_of_Payment_Desc__c = 'xyz'
                           , Company_Number_Pick__c = '701'
                           , Sales_Agent_Email__c = 'test@sample.com' );
            insert a;
        }
        else {
            a = aList[0];
            a.Terms_of_Delivery_Code__c = 'xyz';
            a.Terms_of_Payment_Code__c = 'xyz';
            update a;
        }

    }
}