forEnersys/DavePkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Delivery_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Terms</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Delivery Terms - DT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Accounts (Delivery Terms)</relationshipLabel>
        <relationshipName>Accounts_Delivery_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>End-User</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>BID</fullName>
                </value>
                <value>
                    <fullName>LAD</fullName>
                </value>
                <value>
                    <fullName>LTC</fullName>
                </value>
                <value>
                    <fullName>Power System Provider</fullName>
                </value>
                <value>
                    <fullName>VADs/System Integrator</fullName>
                </value>
                <value>
                    <fullName>Distributor / Agent (excluding VADs)</fullName>
                </value>
                <value>
                    <fullName>Truck Dealer</fullName>
                </value>
                <value>
                    <fullName>Battery Dealers and Distributor</fullName>
                </value>
                <value>
                    <fullName>Key End User</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Armoured Fighting Vehicles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Customer_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SAP Customer Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <label>Distribution Channel Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <label>Sales area Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/Sales_Area_data__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Area Data</relationshipLabel>
        <relationshipName>Sales_Area_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_iD__c</fullName>
        <formula>Account__r.SAP_Customer_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Sales_Organisation_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Code</label>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Sales Area Data</relationshipLabel>
        <relationshipName>Sales_Area_Data</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Conditions</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Shipping Condition - SC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Sales Area Data (Shipping Conditions)</relationshipLabel>
        <relationshipName>Sales_Area_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Area Data</label>
    <nameField>
        <displayFormat>SAD-{0000000}</displayFormat>
        <label>Sales Area Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/SAP_Reference__c.object
<CustomObject>
    <description>This object is for maintaining the information about delivery terms, payment terms, Incoterms, and other tables of reference from Baan or SAP.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP Reference</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/SBQQ__Quote__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <formula>IF(TEXT(CurrencyIsoCode)=&apos;EUR&apos;, TEXT(CurrencyIsoCode), &apos;EUR&apos;)</formula>
        <label>Currency Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Requested_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Terms</label>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Delivery Terms)</relationshipLabel>
        <relationshipName>Quotes_Delivery_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <formula>Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Distribution_Channel_Code__c</formula>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Division_Code__c</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms2_Text__c</fullName>
        <label>Incoterms2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incoterms</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Incoterm - IC</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Incoterms)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms_SAP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria for Payment Terms</errorMessage>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Terms of Payment - TP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Payment Terms)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Information_Number__c</fullName>
        <label>Reference Information Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Quote_Number__c</fullName>
        <label>SAP Quote Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area Data</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
            <filterItems>
                <field>Sales_Area_data__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.SBQQ__Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>MP - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>01</value>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>RP - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>02</value>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>EAS - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>03</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area_data__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <formula>Sales_Area_Data__r.Sales_Office_lookup__r.Code__c</formula>
        <label>Sales Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Sales_Organization__c</formula>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ship_To_Data__c.Sales_Area_Data__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Area_Data__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ship_To_Data__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Conditions</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Shipping Condition - SC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Shipping Conditions)</relationshipLabel>
        <relationshipName>Quotes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
</CustomObject>

forEnersys/DavePkg/objects/Ship_To_Data__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <formula>Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Distribution_Channel_Code__c</formula>
        <label>Distribution Channel Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Id__c</fullName>
        <formula>Sales_Area_Data__r.Account__r.SAP_Customer_Id__c</formula>
        <label>SAP Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Data__c</fullName>
        <label>Sales Area Data</label>
        <referenceTo>Sales_Area_data__c</referenceTo>
        <relationshipLabel>Ship To Data</relationshipLabel>
        <relationshipName>Ship_To_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To Data</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Ship To Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship To Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

forEnersys/DavePkg/classes/SAPCreateQuoteDao.cls
public with sharing class SAPCreateQuoteDao {
	public SAPCreateQuoteDao() {

	}

	public User fetchUserData(Id userId) {
		User returnUser = new User();
		List<User> users = [Select Id, Email From User Where Id = :userId];
		if (users!=null && users.size() > 0) {
			returnUser = users[0];
		}
		return returnUser;
	}

	public SBQQ__Quote__c fetchQuoteData(Id quoteId) {
		SBQQ__Quote__c returnQuote = new SBQQ__Quote__c();
		List<SBQQ__Quote__c> quotes = [Select Id, Name, Currency_Code__c, Customer_Requested_Date__c, Incoterms__c,
											SBQQ__ExpirationDate__c, Valid_From__c, SAP_Quote_Number__c, Shipping_Conditions__c,
											Delivery_Terms__r.Code__c, Delivery_Terms__c, Reference_Information_Number__c, Sales_Office__c,
											Incoterms__r.Code__c, Incoterms2_Text__c, Shipping_Conditions__r.Code__c,
											Distribution_Channel__c, Division__c, Sales_Organization__c,
											Payment_Terms_SAP__c, Payment_Terms_SAP__r.Code__c,
											SBQQ__Account__r.SAP_Customer_Id__c,
											SBQQ__Opportunity2__c,
											Sales_Area_Data__c,
											Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Name,
											Sales_Area_Data__r.Sales_Area_Sales_Organisation_Code__r.Distribution_Channel_Code__c,
											Ship_To_Data__c,
											Ship_To_Data__r.Ship_To_Account__r.SAP_Customer_Id__c
										 From SBQQ__Quote__c Where Id = :quoteId];
		if (quotes!=null && quotes.size() > 0) {
			returnQuote = quotes[0];
		}
		return returnQuote;
	}

	public DaoResults upsertQuotes(List<SBQQ__Quote__c> quotes) {
		DaoResults daoResults = new DaoResults();

		Try {
			if (quotes.size() > 0) {
				daoResults.upsertResults = Database.upsert(quotes, SBQQ__Quote__c.Id, false);
				Utils.logContents('DB Saved upsertQuotes - SBQQ__Quote__c', String.valueOf(quotes));
				Utils.logContents('DB Saved upsertQuotes - upsertResults', String.valueOf(daoResults.upsertResults));
			}
		} Catch(Exception e){
			daoResults.dbException = new DaoException(e.getMessage());
			daoResults.upsertResults = null;
			System.debug('*** DB Save upsertQuotes - Error: ' + e.getMessage());
		}

		return daoResults;
	}

	public class DaoResults {
		public DaoException dbException { get; set; }
		public Database.UpsertResult[] upsertResults { get; set; }

		public DaoResults() {
		}
	}

	public class DaoException extends Exception {}

}