forEnersys/DavePkg/objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

forEnersys/DavePkg/objects/Sales_Area_data__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Conditions</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Shipping Condition - SC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Sales Area Data (Shipping Conditions)</relationshipLabel>
        <relationshipName>Sales_Area_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Area Data</label>
    <nameField>
        <displayFormat>SAD-{0000000}</displayFormat>
        <label>Sales Area Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/SBQQ__Quote__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <formula>IF(TEXT(CurrencyIsoCode)=&apos;EUR&apos;, TEXT(CurrencyIsoCode), &apos;EUR&apos;)</formula>
        <label>Currency Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Requested_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Terms</label>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Delivery Terms)</relationshipLabel>
        <relationshipName>Quotes_Delivery_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incoterms2_Text__c</fullName>
        <label>Incoterms2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incoterms</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Incoterm - IC</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Incoterms)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms_SAP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria for Payment Terms</errorMessage>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Terms of Payment - TP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Payment Terms)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Information_Number__c</fullName>
        <label>Reference Information Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area Data</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
            <filterItems>
                <field>Sales_Area_data__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.SBQQ__Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>MP - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>01</value>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>RP - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>02</value>
            </filterItems>
            <filterItems>
                <field>$Source.SBU__c</field>
                <operation>equals</operation>
                <value>EAS - EMEA</value>
            </filterItems>
            <filterItems>
                <field>Sales_Area_data__c.Division_Code__c</field>
                <operation>equals</operation>
                <value>03</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area_data__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ship_To_Data__c.Sales_Area_Data__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Area_Data__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ship_To_Data__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Conditions</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SAP_Reference__c.Code_Type__c</field>
                <operation>equals</operation>
                <value>Shipping Condition - SC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Reference__c</referenceTo>
        <relationshipLabel>Quotes (Shipping Conditions)</relationshipLabel>
        <relationshipName>Quotes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
</CustomObject>

forEnersys/DavePkg/objects/Ship_To_Data__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area_Data__c</fullName>
        <label>Sales Area Data</label>
        <referenceTo>Sales_Area_data__c</referenceTo>
        <relationshipLabel>Ship To Data</relationshipLabel>
        <relationshipName>Ship_To_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To Data</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Ship To Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship To Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

forEnersys/DavePkg/classes/QuoteSapSyncManager.cls
public with sharing class QuoteSapSyncManager {

	public static final String SETTING_QUOTE_TRIGGER_ENABLED_NAME = 'EMEA Quote Trigger Enabled';

	private Boolean triggerEnabled;
	private Boolean triggerIsInsert;
	private Boolean triggerIsUpdate;
	private Boolean triggerIsDelete;
	private Boolean triggerIsUndelete;
	private Map<Id, SBQQ__Quote__c> triggerOldMap;
	private Map<Id, SBQQ__Quote__c> triggerNewMap;
	private Map<Id, SBQQ__Quote__c> quotesForSync;

	private SapCreateQuoteBso bso;
	private static Map<String,Integration_Settings__c> settings;

	public QuoteSapSyncManager(Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, Map<Id, SBQQ__Quote__c> oldMap, Map<Id, SBQQ__Quote__c> newMap) {
		settings = CustomSettingManager.fetchIntegrationSettingsMapByName();
		triggerEnabled = settings.get(SETTING_QUOTE_TRIGGER_ENABLED_NAME).Boolean_Value__c;

		triggerIsInsert = isInsert;
		triggerIsUpdate = isUpdate;
		triggerIsDelete = isDelete;
		triggerIsUndelete = isUndelete;
		triggerOldMap = oldMap;
		triggerNewMap = newMap;

	}

	public void syncToSap() {
		Map<Id, SBQQ__Quote__c> quotesForSync = new Map<Id, SBQQ__Quote__c>{};

		if (triggerEnabled && triggerNewMap.size()==1) {
			if (!System.isFuture() && !System.isBatch()) {
				if (triggerIsInsert) {
					quotesForSync = triggerNewMap;

				} else if (triggerIsUpdate) {
					quotesForSync = getChangedQuotesFromOldAndNewMaps();

				}

			}

			if (quotesForSync.size() > 0) {
				Utils.logContents('Quotes For Sync (Trigger)', String.valueOf(quotesForSync));

				SObject quoteSObj = (SObject)quotesForSync.values()[0];
				bso = new SapCreateQuoteBso();
				bso.syncQuoteHeaderToSap(quoteSObj);

			}
		}

	}

	private Map<Id, SBQQ__Quote__c> getChangedQuotesFromOldAndNewMaps() {
		Map<Id, SBQQ__Quote__c> returnMap = new Map<Id, SBQQ__Quote__c>{};
		for (Id quoteId : triggerNewMap.keySet()) {
			SBQQ__Quote__c oldQuote = triggerOldMap.get(quoteId);
			SBQQ__Quote__c newQuote = triggerNewMap.get(quoteId);
			if (
				newQuote.Currency_Code__c != oldQuote.Currency_Code__c
				|| newQuote.Customer_Requested_Date__c != oldQuote.Customer_Requested_Date__c
				|| newQuote.Incoterms__c != oldQuote.Incoterms__c
				|| newQuote.Incoterms2_Text__c != oldQuote.Incoterms2_Text__c
				|| newQuote.Payment_Terms_SAP__c != oldQuote.Payment_Terms_SAP__c
				|| newQuote.Shipping_Conditions__c != oldQuote.Shipping_Conditions__c
				|| newQuote.Valid_From__c != oldQuote.Valid_From__c
				|| newQuote.SBQQ__ExpirationDate__c != oldQuote.SBQQ__ExpirationDate__c
				// Delivery Terms have no destination on SAP Quote per Cedric
				//|| newQuote.Delivery_Terms__c != oldQuote.Delivery_Terms__c
				|| newQuote.Reference_Information_Number__c != oldQuote.Reference_Information_Number__c
				|| newQuote.Sales_Area_Data__c != oldQuote.Sales_Area_Data__c
				|| newQuote.Ship_To_Data__c != oldQuote.Ship_To_Data__c
				) {
				returnMap.put(quoteId, newQuote);

			}
		}
		return returnMap;
	}

}