forEnersys/DavePkg/objects/Item_Group__c.object
<CustomObject>
    <description>Item Group table for BaaN Price book integration</description>
    <label>Item Group</label>
    <nameField>
        <displayFormat>IG-{00000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

forEnersys/DavePkg/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Baan_Sales_Price__c</fullName>
        <description>Sales Price from Baan</description>
        <label>Baan Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExtId__c</fullName>
        <externalId>true</externalId>
        <label>ExtId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Item_Group_Desc__c</fullName>
        <description>Description of Item Group (Family)</description>
        <label>Item Group Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Group__c</fullName>
        <label>Item Group</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

forEnersys/DavePkg/classes/PriceBookUtilTest.cls
@isTest(SeeAllData=true)

public class PriceBookUtilTest {
    public static testMethod void testTrigger() {
        List<Product2> pList = [select Id
                                     , Baan_Sales_Price__c
                             		 , Item_Group__c
            			   			 , Item_Group_Desc__c
                        			 , Name
                        			 , CompanyNumber__c
                     			 from Product2
                                order by LastModifiedDate Desc
                                limit 1] ;

        Product2 p;
        if ( pList.isEmpty() ) {
            p = new  Product2( Name = 'Test Prod'
                		     , Baan_Sales_Price__c = 10
                             , Item_Group__c = '12345'
                             , Item_Group_Desc__c = 'aaaa'
                             , CompanyNumber__c = '701' );
        }
        else {
            p = pList[0].clone();
            p.ExtId__c = '';
        }
        insert p;
    }

}